name: cass
dependencies:
  - python=3.10.12
  - jupyterlab
  - pip=23.1.2
  - pip:
    - black
    - numpy
    - scikit-learn==1.3.1
    - spacy==3.7.1
    - https://github.com/explosion/spacy-models/releases/download/fr_core_news_sm-3.7.0/fr_core_news_sm-3.7.0.tar.gz#egg=fr_core_news_sm
